### ISSUE TITLE
error while evaluating conditional: ansible_os_family == 'Debian'

### ISSUE THREAD

**Issue by makmanalp** [Stouts/Stouts.redis#2]
I keep getting this (Ubuntu 13.10 saucy, within vagrant)

```
TASK: [redis | redis-install | Add repository] ********************************
fatal: [default] => error while evaluating conditional: ansible_os_family == 'Debian'
```

**Comment by nerdyness** [comment]
> Solved: entirely my fault. For some reason gather_facts was set to False. Cheers!

Life safer! :+1: Thanks

**Comment by miskolc** [comment]
> Solved: entirely my fault. For some reason gather_facts was set to False. Cheers!

Mine too!

`
>
